name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: elementary/docker:unstable
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y gobject-introspection libglib2.0-dev libgranite-dev libwingpanel-2.0-dev libxml2-dev meson valac
    - name: Build
      run: |
        meson build
        ninja -C build
