name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: elementary/docker:unstable

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          apt update
          apt install -y gobject-introspection libglib2.0-dev libgranite-dev libwingpanel-dev libibus-1.0-dev libxml2-dev meson valac
      - name: Build
        env:
          DESTDIR: out
        run: |
          meson build
          ninja -C build
          ninja -C build install

  lint:
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: io.elementary.vala-lint -d .
